# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
        ('impuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpuestoPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impuesto.Impuesto')),
                ('id_presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuesto.Presupuesto')),
            ],
        ),
    ]
