# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('tipo_presupuesto', '0001_initial'),
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_confeccion', models.DateField()),
                ('fecha_ultima_modificacion', models.DateField()),
                ('divisa', models.CharField(max_length=100)),
                ('gasto_general', models.IntegerField()),
                ('utilidad', models.IntegerField()),
                ('redondeo', models.IntegerField()),
                ('decimal', models.IntegerField()),
                ('valor_total', models.IntegerField()),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
                ('id_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obra.Obra')),
                ('id_tipo_presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_presupuesto.TipoPresupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'ordering': ('nombre', 'fecha_confeccion', 'valor_total'),
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
