# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('tipo_usuario',),
            },
        ),
    ]
