# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_usuario',
            options={'ordering': ('tipo_usuario',), 'verbose_name': 'Tipo de Usuario', 'verbose_name_plural': 'Tipos de Usuario'},
        ),
    ]
