# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
        ('partida', '0001_initial'),
        ('unidad_medida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida_interno', models.CharField(max_length=200)),
                ('partida_externo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('id_partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_partida', to='partida.Partida')),
                ('id_partida_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_partida_padre', to='partida.Partida')),
                ('id_presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuesto.Presupuesto')),
                ('id_unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad_medida.UnidadMedida')),
            ],
            options={
                'ordering': ('partida_interno', 'partida_externo'),
                'verbose_name': 'Detalle presupuesto',
                'verbose_name_plural': 'Detalle presupuesto',
            },
        ),
    ]
