# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mandante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('giro', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mandante',
                'ordering': ('nombre',),
                'verbose_name_plural': 'Mandantes',
            },
        ),
    ]
