# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandante',
            options={'ordering': ('nombre',), 'verbose_name': 'Mandante', 'verbose_name_plural': 'Mandantes'},
        ),
    ]
