# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandante', '0002_auto_20160803_2029'),
        ('empresa', '0003_auto_20160803_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_contrato', models.DateField()),
                ('fecha_final', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('archivo', models.ImageField(blank=True, upload_to='')),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
                ('id_mandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mandante.mandante')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ('nombre',),
            },
        ),
    ]
