# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 01:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2016, 8, 6, 1, 59, 36, 61767, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
