# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('rut', models.IntegerField()),
                ('digito_verificador', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('representate', models.CharField(max_length=255)),
            ],
        ),
    ]
